# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-16 14:09
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('price', models.IntegerField()),
                ('option', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('items', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=250), default=None, null=True, size=None)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
