# Generated by Django 2.2.3 on 2019-07-17 18:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('soft_deleted', models.BooleanField(default=False, editable=False)),
                ('value', models.SlugField()),
            ],
            options={
                'verbose_name': 'Option',
                'verbose_name_plural': 'Options',
            },
        ),
        migrations.CreateModel(
            name='OptionSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('soft_deleted', models.BooleanField(default=False, editable=False)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Option Set',
                'verbose_name_plural': 'Option Sets',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('soft_deleted', models.BooleanField(default=False, editable=False)),
                ('total_price', models.BigIntegerField(blank=True, editable=False, null=True)),
                ('consume_location', models.CharField(choices=[('in', 'In Shop'), ('out', 'Take Away')], max_length=3)),
                ('delivery_address', models.TextField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('soft_deleted', models.BooleanField(default=False, editable=False)),
                ('name', models.CharField(max_length=80)),
                ('price', models.IntegerField(default=10000, help_text='Enter price value in Toman currency')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('soft_deleted', models.BooleanField(default=False, editable=False)),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ordering.Option')),
                ('option_set', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ordering.OptionSet')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ordering.Order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ordering.Product')),
            ],
            options={
                'verbose_name': 'Order Item',
                'verbose_name_plural': 'Order Items',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(related_name='orders', through='ordering.OrderItem', to='ordering.Product'),
        ),
        migrations.AddField(
            model_name='optionset',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='option_sets', to='ordering.Product'),
        ),
        migrations.AddField(
            model_name='option',
            name='option_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='ordering.OptionSet'),
        ),
        migrations.AlterUniqueTogether(
            name='optionset',
            unique_together={('name', 'product')},
        ),
        migrations.AlterUniqueTogether(
            name='option',
            unique_together={('option_set', 'value')},
        ),
    ]
