# Generated by Django 2.2.3 on 2019-07-16 19:31

from django.db import migrations


def initial_products(apps, schema_editor):
    """
    Initial Default Products
    """
    Option = apps.get_model('ordering', 'Option')
    OptionSet = apps.get_model('ordering', 'OptionSet')
    Product = apps.get_model('ordering', 'Product')
    # create products
    products = [
        {
            'name': 'Latte',
            'option_sets': [
                {
                    'name': 'Milk',
                    'options': [
                        'skim', 'semi', 'whole'
                    ]
                }
            ]
        },
        {
            'name': 'Cappuccino',
            'option_sets': [
                {
                    'name': 'Size',
                    'options': [
                        'small', 'medium', 'large'
                    ]
                }
            ]
        },
        {
            'name': 'Espresso',
            'option_sets': [
                {
                    'name': 'Shots',
                    'options': [
                        'single', 'double', 'triple'
                    ]
                }
            ]
        },
        {
            'name': 'Tea'
        },
        {
            'name': 'Hot chocolate',
            'option_sets': [
                {
                    'name': 'Size',
                    'options': [
                        'small', 'medium', 'large'
                    ]
                }
            ]
        },
        {
            'name': 'Cookie',
            'option_sets': [
                {
                    'name': 'Kind',
                    'options': [
                        'chocolate chip', 'ginger'
                    ]
                }
            ]
        }
    ]
    for product_info in products:
        product = Product(name=product_info['name'])
        product.save()
        for option_set_info in product_info.get('option_sets', []):
            option_set = OptionSet(name=option_set_info['name'], product=product)
            option_set.save()
            for option_value in option_set_info['options']:
                Option.objects.create(value=option_value, option_set=option_set)


class Migration(migrations.Migration):
    dependencies = [
        ('ordering', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(initial_products)
    ]
