# Generated by Django 2.2.3 on 2019-07-17 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0002_auto_20190717_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='option',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ordering.Option'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='option_set',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ordering.OptionSet'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='items', to='ordering.Order'),
        ),
    ]
