# Generated by Django 4.0.2 on 2022-02-01 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availableproductoption',
            name='name',
            field=models.CharField(blank=True, choices=[('Milk', 'Milk'), ('Size', 'Size'), ('Shots', 'Shots'), ('Kind', 'Kind'), ('Consume location', 'Consume location')], max_length=512, null=True),
        ),
    ]
