# Generated by Django 4.0.2 on 2022-02-01 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_availableproductoption_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='availableproductoption',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1.5, max_digits=10),
        ),
        migrations.AlterField(
            model_name='availableproductoption',
            name='option',
            field=models.CharField(blank=True, choices=[('Skim', 'Skim'), ('Semi', 'Semi'), ('Whole', 'Whole'), ('Small', 'Small'), ('Medium', 'Medium'), ('Large', 'Large'), ('Single', 'Single'), ('Double', 'Double'), ('Triple', 'Triple'), ('Chocolate', 'Chocolate'), ('Chip', 'Chip'), ('Ginger', 'Ginger'), ('take away', 'take away'), ('In shop', 'In shop')], max_length=512, null=True),
        ),
    ]
