# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-25 10:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
