# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-22 22:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_remove_order_item_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_item',
            name='order',
        ),
        migrations.RemoveField(
            model_name='order_item',
            name='product',
        ),
        migrations.RemoveField(
            model_name='order_item',
            name='varient',
        ),
        migrations.RemoveField(
            model_name='varient',
            name='order',
        ),
        migrations.AddField(
            model_name='order',
            name='varient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='manager.Varient'),
        ),
        migrations.AddField(
            model_name='varient',
            name='option',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='manager.Option'),
        ),
        migrations.DeleteModel(
            name='Order_item',
        ),
    ]
