# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-21 21:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('handler', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='consume_place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='handler.Place'),
        ),
    ]
