# Generated by Django 2.1.2 on 2020-02-17 23:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('coffeeshop', '0003_auto_20200217_1941'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('status', django_fsm.FSMField(default='waiting', max_length=50, protected=True, verbose_name='Status')),
                ('total_price', models.PositiveIntegerField(default=0, verbose_name='Total Price')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Customer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('count', models.PositiveIntegerField(verbose_name='Count')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='coffeeshop.Order', verbose_name='Order')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='customizableattribute',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Attribute Name'),
        ),
        migrations.AlterField(
            model_name='customizableattributeoption',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Option Name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='customizable_attributes',
            field=models.ManyToManyField(blank=True, to='coffeeshop.CustomizableAttribute'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='coffeeshop.Product', verbose_name='Product'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='selected_options',
            field=models.ManyToManyField(blank=True, to='coffeeshop.CustomizableAttributeOption'),
        ),
    ]
