# Generated by Django 2.1.2 on 2020-02-18 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coffeeshop', '0004_auto_20200217_2344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customizableattribute',
            name='status',
        ),
        migrations.RemoveField(
            model_name='customizableattributeoption',
            name='status',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='status',
        ),
        migrations.RemoveField(
            model_name='product',
            name='status',
        ),
    ]
