# Generated by Django 2.1.2 on 2020-02-18 05:47

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('coffeeshop', '0005_auto_20200218_0532'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
        migrations.AddField(
            model_name='order',
            name='state',
            field=django_fsm.FSMField(default='waiting', max_length=50, protected=True, verbose_name='Status'),
        ),
    ]
