# Generated by Django 2.2 on 2019-05-02 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('wa', 'waiting'), ('pr', 'preparation'), ('rd', 'ready'), ('de', 'delivered'), ('uk', 'unknown')], max_length=2)),
                ('consume_location', models.CharField(choices=[('sh', 'in shop'), ('ta', 'takeaway')], max_length=2)),
                ('total_price', models.PositiveIntegerField(verbose_name='Total Price')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Name')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='Password')),
                ('email', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Email Address')),
                ('join_date', models.DateTimeField(auto_now_add=True, verbose_name='Joined Date')),
            ],
        ),
        migrations.CreateModel(
            name='ProductOrderType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('product_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='restbucks.ProductType')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('image', models.URLField(blank=True, null=True, verbose_name='Image URL')),
                ('price', models.PositiveIntegerField(verbose_name='Price')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('kind', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='restbucks.ProductType')),
            ],
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='restbucks.Order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='restbucks.Product')),
                ('product_order_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='restbucks.ProductOrderType')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='restbucks.User'),
        ),
    ]
