# Generated by Django 2.2 on 2019-05-02 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restbucks', '0003_auto_20190502_1001'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='price',
            field=models.PositiveIntegerField(default=0, verbose_name='Price'),
            preserve_default=False,
        ),
    ]
