# Generated by Django 2.2 on 2019-05-02 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restbucks', '0004_orderproduct_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproduct',
            name='price',
            field=models.PositiveIntegerField(default=0, verbose_name='Price'),
        ),
    ]
