# Generated by Django 2.2 on 2019-05-02 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restbucks', '0006_auto_20190502_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproduct',
            name='product_order_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='restbucks.ProductOrderType'),
        ),
    ]
