# Generated by Django 2.2 on 2019-05-02 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restbucks', '0007_auto_20190502_1908'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='count',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Count'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('wa', 'waiting'), ('pr', 'preparation'), ('rd', 'ready'), ('de', 'delivered'), ('ca', 'cancel'), ('uk', 'unknown')], default='wa', max_length=2),
        ),
    ]
