# Generated by Django 2.2 on 2019-05-02 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restbucks', '0008_auto_20190503_0111'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
