# Generated by Django 4.0.2 on 2022-02-01 21:04

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.utcnow)),
                ('updated_at', models.DateTimeField(blank=True, default=datetime.datetime.utcnow)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('status', models.CharField(choices=[('Waiting', 'Waiting'), ('Preparation', 'Preparation'), ('Ready', 'Ready'), ('Delivered', 'Delivered'), ('Canceled', 'Canceled')], default='Waiting', max_length=32)),
                ('total_price', models.DecimalField(decimal_places=2, default=10.0, max_digits=10)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.utcnow)),
                ('updated_at', models.DateTimeField(blank=True, default=datetime.datetime.utcnow)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('price', models.DecimalField(decimal_places=2, default=10.0, max_digits=10)),
                ('option', models.CharField(default='', max_length=32)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
