# Generated by Django 3.1.7 on 2021-03-06 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConsumeLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='FeaturesValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restbuck_app.feature')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.SmallIntegerField(choices=[(0, 'waiting'), (1, 'preparation'), (2, 'ready'), (3, 'delivered')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('cost', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ProductOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('consume_location', models.SmallIntegerField(choices=[(0, 'take away'), (1, 'in shop')])),
            ],
        ),
        migrations.CreateModel(
            name='ProductOrderFeatureValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_List', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restbuck_app.featuresvalue')),
                ('product_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restbuck_app.productorder')),
            ],
        ),
        migrations.AddField(
            model_name='productorder',
            name='feature_value_list',
            field=models.ManyToManyField(through='restbuck_app.ProductOrderFeatureValue', to='restbuck_app.FeaturesValue'),
        ),
        migrations.AddField(
            model_name='productorder',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restbuck_app.order'),
        ),
        migrations.AddField(
            model_name='productorder',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restbuck_app.product'),
        ),
        migrations.CreateModel(
            name='ProductFeature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restbuck_app.feature')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restbuck_app.product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='feature_list',
            field=models.ManyToManyField(through='restbuck_app.ProductFeature', to='restbuck_app.Feature'),
        ),
        migrations.AddField(
            model_name='order',
            name='product_list',
            field=models.ManyToManyField(related_name='products', through='restbuck_app.ProductOrder', to='restbuck_app.Product'),
        ),
    ]
