# Generated by Django 3.1.7 on 2021-03-09 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restbuck_app', '0003_auto_20210308_2025'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productorderfeaturevalue',
            old_name='feature_List',
            new_name='feature_value',
        ),
    ]
