# Generated by Django 3.1.7 on 2021-03-09 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restbuck_app', '0004_auto_20210309_1131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productorder',
            name='feature_value_list',
        ),
        migrations.AddField(
            model_name='productorder',
            name='feature_value',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='restbuck_app.featuresvalue'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'waiting'), (1, 'preparation'), (2, 'ready'), (3, 'delivered'), (4, 'canceled')], default=0),
        ),
    ]
