# Generated by Django 3.1.7 on 2021-03-09 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restbuck_app', '0005_auto_20210309_1807'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductOrderFeatureValue',
        ),
    ]
