# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-20 12:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cunsumelocation',
            field=models.CharField(choices=[('TA', 'takeaway'), ('IS', 'inshop')], default='IS', max_length=2),
        ),
    ]
