# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-05-21 22:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_order_cunsumelocation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('customer_email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Order_item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Varient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django-restbucks-challenge.manager.Option')),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='cunsumelocation',
        ),
        migrations.RemoveField(
            model_name='order',
            name='customerEmail',
        ),
        migrations.RemoveField(
            model_name='product',
            name='datetime',
        ),
        migrations.RemoveField(
            model_name='product',
            name='option1',
        ),
        migrations.RemoveField(
            model_name='product',
            name='option2',
        ),
        migrations.RemoveField(
            model_name='product',
            name='option3',
        ),
        migrations.AddField(
            model_name='order',
            name='consume_location',
            field=models.CharField(choices=[('TA', 'take away'), ('IS', 'in shop')], default='IS', max_length=2),
        ),
        migrations.AddField(
            model_name='order_item',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django-restbucks-challenge.manager.Order'),
        ),
        migrations.AddField(
            model_name='order_item',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django-restbucks-challenge.manager.Product'),
        ),
        migrations.AddField(
            model_name='order_item',
            name='varient',
            field=models.ManyToManyField(to='django-restbucks-challenge.manager.Varient'),
        ),
        migrations.AddField(
            model_name='option',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django-restbucks-challenge.manager.Product'),
        ),
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='django-restbucks-challenge.manager.Customer'),
        ),
    ]
